//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refwebportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int Id { get; set; }
        public int GamePlayerId { get; set; }
        public System.TimeSpan GoalTime { get; set; }
        public bool IsOwnGoal { get; set; }
    
        public virtual GamePlayer GamePlayer { get; set; }
    }
}
