//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refwebportal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FROdataEntities3 : DbContext
    {
        public FROdataEntities3()
            : base("name=FROdataEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GamePlayer> GamePlayers { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameTeam> GameTeams { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<Penalty> Penalties { get; set; }
        public virtual DbSet<PenaltyType> PenaltyTypes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Substitution> Substitutions { get; set; }
        public virtual DbSet<Team> Teams { get; set; }

        public System.Data.Entity.DbSet<refwebportal.Models.ViewPlayers> ViewPlayers { get; set; }
    }
}
