//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refwebportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitution
    {
        public int Id { get; set; }
        public int GamePlayerGoingOffTheFieldId { get; set; }
        public int GamePlayerGoingOnTheFieldId { get; set; }
        public System.TimeSpan SubstitutionTime { get; set; }
        public Nullable<int> GamePlayer_Id { get; set; }
    
        public virtual GamePlayer GamePlayer { get; set; }
        public virtual GamePlayer GamePlayer1 { get; set; }
        public virtual GamePlayer GamePlayer2 { get; set; }
    }
}
